#!/usr/bin/env bash

function require_brew() {
  running "brew install $1 $2"
  brew list $1 > /dev/null 2>&1 | true
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    action "brew install $1 $2"
    brew install $1 $2
    if [[ $? != 0 ]]; then
      error "failed to install $1! aborting..."
      exit -1
    fi
  fi
  ok
}

function cask_install() {
  running "brew cask $1"
  brew cask search $1 > /dev/null 2>&1 | true
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    action "brew cask install $1 $2"
    brew cask install $1 $2
    if [[ $? != 0 ]]; then
      error "failed to install $1! aborting..."
      exit -1
    fi
  fi
  ok
}

########## BREW PKGS ##########
running "installing python"
require_brew python

running "installing exa"
require_brew exa

running "installing zsh"
require_brew zsh

running "installing zsh-autosuggestions"
require_brew zsh-autosuggestions

########## APPS ###########
running "installing brew cask"
brew tap caskroom/cask

#### DEVELOPMENT ####
yes_or_no "would you like to install iterm2?"
if confirmed; then
  cask_install iterm2
fi

yes_or_no "would you like to install visual-studio-code?"
if confirmed; then
  cask_install visual-studio-code
fi

#### MEDIA ####
yes_or_no "would you like to install vlc?"
if confirmed; then
  cask_install vlc
fi

yes_or_no "would you like to install spotify?"
if confirmed; then
  cask_install spotify
fi

#### COMMUNICATION ####
yes_or_no "would you like to install slack?"
if confirmed; then
  cask_install slack
fi

#### MISC ####
yes_or_no "would you like to install google chrome?"
if confirmed; then
  cask_install google-chrome
fi

yes_or_no "would you like to install flux?"
if confirmed; then
  cask_install flux
fi

yes_or_no "would you like to install google-backup-and-sync?"
if confirmed; then
  cask_install google-backup-and-sync
fi

running "cleaning up cask files"
brew cleanup

bot "chosen brew and brew cask packages installed successfully"
